// src/app/components/navigation/login-modal.component.ts
import { Component, Injectable } from '@angular/core';
import { NgbActiveModal, NgbModal } from '@ng-bootstrap/ng-bootstrap';

declare const window: Window;

@Injectable()
export class LoginModalService {

  constructor(private modalService: NgbModal) {
  }

  open() {
    return this.modalService.open(LoginModalComponent, { size: 'sm' }).result
  }
}

@Component({
  selector: 'app-login-modal',
  styleUrls: ['./login-modal.component.scss'],
  template: `
    <div class="modal-header">
      <h4 class="modal-title">
        <a><i class="fa fa-times" (click)="cancel()"></i></a>
        <span translate>Login</span>
      </h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          <p translate>eDuuni information</p>
          <p translate>Login information</p>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-action" (click)="login()" translate>Log In</button>
      <button type="button" class="btn btn-action" (click)="register()" translate>Register</button>
    </div>
  `
})
export class LoginModalComponent {

  constructor(private modal: NgbActiveModal) {
  }

  cancel() {
    this.modal.dismiss('cancel');
  }

  login() {
    const currentUrl = window.location.href;
    window.location.href = `/Shibboleth.sso/Login?target=${encodeURIComponent(currentUrl)}`;
  }

  register() {
    window.open('http://id.eduuni.fi/signup', '_blank');
  }
}

// src/common/components/login-modal/login-modal.tsx
import {
  ModalBackdrop,
  ModalWindow,
  ModalDialog,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  Row,
  ColMd12,
} from './login-modal.styles';
import { Button as SuomiButton } from 'suomifi-ui-components';
import { LoginModalFunctions } from '../../interfaces/callback-interfaces';
import { useTranslation } from 'next-i18next';

export default function LoginModalView({
  modalFunctions,
}: {
  modalFunctions: LoginModalFunctions;
}) {
  const { t } = useTranslation('common');

  return (
    <>
      <ModalBackdrop></ModalBackdrop>
      <ModalWindow>
        <ModalDialog>
          <ModalContent>
            <ModalHeader>
              <h4 className="modal-title">
                {/* <a><i id="close_login_modal_link" className="fa fa-times" onClick={modalFunctions.closeModal}></i></a>     */}
                <SuomiButton onClick={modalFunctions.closeModal}>X</SuomiButton>
                <span>Login</span>
              </h4>
            </ModalHeader>
            <ModalBody>
              <Row>
                <ColMd12>
                  <p>
                    { t('terminology-login-description-1') }
                  </p>
                  <p>
                    { t('terminology-login-description-2') }
                  </p>
                </ColMd12>
              </Row>
            </ModalBody>
            <ModalBody>
              <Row>
                <ModalFooter>
                  <SuomiButton
                    id="login_modal_button"
                    type="button"
                    className="btn btn-action"
                    onClick={login}
                  >
                    Log In
                  </SuomiButton>
                  <SuomiButton
                    id="register_login_modal_button"
                    type="button"
                    className="btn btn-action"
                    onClick={register}
                  >
                    Register
                  </SuomiButton>
                </ModalFooter>
              </Row>
            </ModalBody>
          </ModalContent>
        </ModalDialog>
      </ModalWindow>
    </>
  );

  function login() {
    window.location.href = '/Shibboleth.sso/Login?target=/';
  }

  function register() {
    window.open('http://id.eduuni.fi/signup', '_blank');
  }
}
